### ISSUE TITLE
Investigate or document data selection patterns

### ISSUE THREAD

**Issue by markerikson** [rtk-incubator/rtk-query#79]
Seen a couple comments on this idea and I think there's good reason to support it.

Right now, it's possible to have both a "fetch all posts" query, and a "fetch one post by ID" query.  But, those end up as two separate queries with separate caches.  It seems like there's a missed use case: "fetch all the posts", but then "select one item out of that 'all posts' cache by ID".  Loosely put, I'm picturing something like:

```js
  const selectPostById = createSelector(
    postsApi.selectors.selectAllPosts,
    (state, postId) => postId,
    (posts, postId) => posts.find(p => p.id === postId)
  )

// later
  const post = useSelector(state => selectPostById(state, props.postId))
```

Maybe that's entirely doable already and I just haven't actually looked at the API enough to know if this is correct :) 

Related: it's a common Redux pattern to have a list parent select _just_ an array of item IDs from the store, as a stable reference, and then render a list of `<ListItem key={id} id={id} />`, possibly with the children being memoized.  Then, if a data item does get updated, the parent either continues to get the same array of IDs as doesn't re-render at all, or at least all the children are memoized and don't re-render.

How feasible is it to select item IDs from this, ideally using a stable array ref?

**Comment by markerikson** [comment]
Update: after poking around at the example "React Hooks" sandbox for a few minutes, I came up with:

```ts
// Surprise here: this _creates_ a new selector, and apparently optionally takes a Symbol?  
// Is that really what we want to expose publicly?
const selectPosts =  postApi.selectors.query.getPosts();
const defaultPostIds : Post['id'][] = [];

const selectPostIds = createSelector(
  (state: RootState) => selectPosts(state).data,
  (posts) => {
   if (posts) {
     return posts.map(post => post.id);
   } 
   return defaultPostIds;
  }
)

const PostList2 = () => {
  // type: number[]
  const posts = useSelector(selectPostIds)
}
```

**Comment by phryneas** [comment]
```
// Surprise here: this _creates_ a new selector, and apparently optionally takes a Symbol?  
// Is that really what we want to expose publicly?
const selectPosts =  postApi.selectors.query.getPosts();
```
the symbol part is weird, gotta take a look at that, but yes, it creates a selector. Arguments are essentially pre-bound there.
Assume you have `getPost(postId)` instead of a query without arguments.

```
const selectPostForId5 =  postApi.selectors.query.getPost(5);
const selectPostForId7 =  postApi.selectors.query.getPost(7);
```


Also: that is a very old API that should not be in there. It should be `postApi.endpoints.posts.select` by now - in which example are you digging around there? :D

**Comment by phryneas** [comment]
Just as a braindump:

Either
```ts
useFetchPostsQuery({page: 1}, {skipSelecting: true});
// manually use useSelector here
```

or something like

```ts
useFetchPostsQuery({ page: 1 }, { selectFromResult: post => posts.map(post => post.id) });
```

I prefer the second one, but that `selectFromResult` would need to be memoized & shallow-compared internally somehow.

**Comment by markerikson** [comment]
I was specifically looking at the `PostsManager.tsx` component in the "React Hooks" example sandbox.

I could get behind the `selectFromResult` idea, yeah.  A caveat here is that I could see users wanting to do a complete selection from other parts of the state, similar to how I was doing it above.  So, maybe the path here is to provide this `selectFromResult` option for "use the query, but just grab out part of it" (and leave the user responsible for memoizing as normal), but also document "here's how to use the generated selectors to write your own selectors".

**Comment by phryneas** [comment]
Thinking about this a bit more, I'm leaning heavily towards the `useFetchPostsQuery({page: 1}, {skipSelecting: true});` option, combined with manual selecting.

The problem with anything else would be that the transaction state would still change, so `isLoading` would swap between `true` and `false` and cause rerenders, no matter if this had any consequence for the selected sub-result.

**Comment by markerikson** [comment]
I think Tanner said that R-Q has some kind of a `select` option:

https://twitter.com/tannerlinsley/status/1334555922685804544

But I don't see it mentioned in their docs or code anywhere.

Closest I can find is the discussion in these issues:

- https://github.com/tannerlinsley/react-query/issues/772#issuecomment-694301450
- https://github.com/tannerlinsley/react-query/issues/772#issuecomment-721383714
- https://github.com/tannerlinsley/react-query/pull/883#issuecomment-675889556

**Comment by phryneas** [comment]
msutkowski
>can you explain this thing to me
>>Thinking about this a bit more, I'm leaning heavily towards the useFetchPostsQuery({page: 1}, {skipSelecting: true}); option, combined with manual selecting.    

> The problem with anything else would be that the transaction state would still change, so isLoading would swap between true and false and cause rerenders, no matter if this had any consequence for the selected sub-result.
what would skipSelecting actually be doing there?

phryneas
> it would, just like skip: true cause the useSelector call to just always return the uninitialized value
So the hook still registers as a query value subscriber to prevent cleanup, causes data to be fetched etc., but it does not subscribe to state changes that might cause rerenders
Pretty much a prefetch with a subscribe: true

msutkowski
> yea
and you're opposed to just including the selector?
i think it seems to strange to subscribe, then select in two calls

phryneas
> From a TS perspective, that seems like the worst case
Because either that would select the whole state first, to give you the isLoading etc. values - that way the hook call would retain the structure of the return value, but also re-render every time loading state changes (which we want to avoid here)
Or it would skip selecting isLoading etc. and just select that one value, completely changing the shape of the return value

msutkowski
>got it.
thank you :slight_smile:

phryneas
>I mean, we could kinda merge those.
Add another isSelected flag here. isLoading etc. will be undefined and data will be SelectorResult | undefined, because we don't really know about that
But all that makes it kinda more complex - not only on our side, but also to use it.
So I'd just opt for isUninitialized and have the user select in a manual useSelector
I mean, we could also split that up a bit
Create two new hooks api.endpoint.useQuerySubscription(arg, options), api.endpoint.useQueryStatus(arg, selector?)  where useQueryStatus without an argument would return the flags and data - and with an selector argument would only return whatever that selector returned.
And make useQuery just call these two hooks, but also provide them as primitives to the user.

msutkowski
>yea
my only thought here is i'd prefer to not have people doing useSelector(anything)
i get that regular redux users are used to it, but if we can abstract that away and make it seem like a part of rtkq, awesome
if that makes sense? :smile:

phryneas
>Yup. Mind me copy&pasting this conversation into github? :slight_smile:

msutkowski
>nope!

**Comment by markerikson** [comment]
I kinda like R-Q's usage here:

```js
import { useQuery } from 'react-query'

function User() {
   const { data } = useQuery('user', fetchUser, {
     select: user => user.username,
   })
   return <div>Username: {data}</div>
}
```

> Set the `notifyOnChangeProps` option to `['data', 'error']` to only re-render when the selected data changes.

**Comment by airjp73** [comment]
I also like the `select` option being passed to the hook. Or another hook that has support for that would be fine too.

Going further, it could be nice to a `createEntityAdapter` style api to pull items out (and for optimistic updates).
